service: task-management-service
frameworkVersion: "3"

package:
  # individually: true
  excludeDevDependencies: true
  exclude:
    - src/**
    - .jest/**
    - scripts/**
    - .eslintrc.yaml
    - .gitignore
    - jest.config.ts
    - makefile
    - readme.md
    - tsconfig.json
    - yarn.lock

plugins:
  - serverless-deployment-bucket
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:* # allows all dynamodb actions
          Resource:
            - Fn::GetAtt: [TMSSystemTable, Arn]
            - Fn::Join:
                - "/"
                - - Fn::GetAtt: [TMSSystemTable, Arn]
                  - "index/*"
  environment:
    stage: ${opt:stage, self:provider.stage}
  httpApi:
    cors: true
    authorizers:
      internalAuthorizer:
        type: request
        functionName: internal_authorizer
        identitySource:
          - $request.header.Authorization
        enableSimpleResponses: true
        payloadVersion: "2.0"
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-deployment-bucket
    blockPublicAccess: true

resources:
  Resources:
    TMSSystemTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "TMSSystemTable"
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: "S"
          - AttributeName: "sk"
            AttributeType: "S"
          - AttributeName: "entity_type"
            AttributeType: "S"
          - AttributeName: "status"
            AttributeType: "S"
          - AttributeName: "due_date"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "pk"
            KeyType: "HASH"
          - AttributeName: "sk"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "statusIndex"
            KeySchema:
              - AttributeName: "pk"
                KeyType: "HASH"
              - AttributeName: "status"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: "dueDateIndex"
            KeySchema:
              - AttributeName: "pk"
                KeyType: "HASH"
              - AttributeName: "due_date"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: "EntityTypeIndex"
            KeySchema:
              - AttributeName: "pk"
                KeyType: "HASH"
              - AttributeName: "entity_type"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"

    FileInventoryBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "file-inventory-bucket-yaho"
        AccessControl: "Private"
        VersioningConfiguration:
          Status: "Enabled"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        LifecycleConfiguration:
          Rules:
            - Id: "DeleteOldFiles"
              Status: "Enabled"
              ExpirationInDays: 30 # 30일 후 파일 삭제

    TaskNotificationTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "task-notification-topic"
        DisplayName: "Task Notification Topic"
        Subscription:
          - Endpoint: "roy@reconlabs.ai"
            Protocol: "email"

functions:
  s3ObjectCreatedEventFunction:
    handler: dist/lambda/event/s3-object-created/index.handler
    events:
      - s3:
          bucket: !Ref FileInventoryBucket
          event: s3:ObjectCreated:*
          existing: true
  v1_auth_google_authorize:
    handler: dist/routes/v1/auth/google/authorize/index.handler
    events:
      - httpApi:
          method: POST
          path: /v1/auth/google/authorize
  v1_auth_google_refresh:
    handler: dist/routes/v1/auth/google/refresh/index.handler
    events:
      - httpApi:
          method: POST
          path: /v1/auth/google/refresh
  v1_auth_google_revoke:
    handler: dist/routes/v1/auth/google/revoke/index.handler
    events:
      - httpApi:
          method: POST
          path: /v1/auth/google/revoke
  v1_file_list:
    handler: dist/routes/v1/file/list/index.handler
    events:
      - httpApi:
          method: GET
          path: /v1/files
          authorizer:
            name: internalAuthorizer
  v1_file_upload:
    handler: dist/routes/v1/file/upload/index.handler
    events:
      - httpApi:
          method: POST
          path: /v1/files/upload
          authorizer:
            name: internalAuthorizer
  v1_task_create:
    handler: dist/routes/v1/task/create/index.handler
    events:
      - httpApi:
          method: POST
          path: /v1/tasks
          authorizer:
            name: internalAuthorizer
  v1_task_list:
    handler: dist/routes/v1/task/list/index.handler
    events:
      - httpApi:
          method: GET
          path: /v1/tasks
          authorizer:
            name: internalAuthorizer
  v1_task_update:
    handler: dist/routes/v1/task/update/index.handler
    events:
      - httpApi:
          method: PUT
          path: /v1/tasks/{task_id}
          authorizer:
            name: internalAuthorizer
  v1_task_delete:
    handler: dist/routes/v1/task/delete/index.handler
    events:
      - httpApi:
          method: DELETE
          path: /v1/tasks/{task_id}
          authorizer:
            name: internalAuthorizer
  v1_me_get:
    handler: dist/routes/v1/me/get/index.handler
    events:
      - httpApi:
          method: GET
          path: /v1/me
          authorizer:
            name: internalAuthorizer

  internal_docs_html:
    handler: dist/routes/internal/docs/html/index.handler
    events:
      - httpApi:
          method: GET
          path: /internal/docs/html
  internal_docs_json:
    handler: dist/routes/internal/docs/json/index.handler
    events:
      - httpApi:
          method: GET
          path: /internal/docs/json
  internal_docs_yaml:
    handler: dist/routes/internal/docs/yaml/index.handler
    events:
      - httpApi:
          method: GET
          path: /internal/docs/yaml
  internal_health:
    handler: dist/routes/internal/health/index.handler
    events:
      - httpApi:
          method: GET
          path: /internal/health
  internal_authorizer:
    handler: dist/lambda/authorizer/index.handler

  NotificationLambda:
    handler: dist/lambda/stream/ddb-record-changed/index.handler
